//! `fg undo` — reset the most recent auto-commit(s) back to the index.
//!
//! The commits are soft-reset (HEAD~N), so all changes land back in the
//! staging area. No work is lost.

use anyhow::{anyhow, Context, Result};
use chrono::{DateTime, Utc};
use std::path::PathBuf;
use tracing::info;

/// Information about a commit that was undone.
#[derive(Debug, Clone)]
pub struct UndoneCommit {
    pub oid: String,
    pub message: String,
    pub files: usize,
    pub committed_at: DateTime<Utc>,
}

/// Soft-reset the last `count` commits, returning them to the index.
///
/// Only undoes commits whose message was generated by `fg` (conventional
/// commit format or `auto:` prefix).  Passing `force = true` skips that
/// guard and undoes unconditionally.
pub async fn undo_last(repo_root: PathBuf, count: usize, force: bool) -> Result<Vec<UndoneCommit>> {
    tokio::task::spawn_blocking(move || undo_last_sync(&repo_root, count, force))
        .await
        .context("spawn_blocking join")?
}

fn undo_last_sync(repo_root: &std::path::Path, count: usize, force: bool) -> Result<Vec<UndoneCommit>> {
    if count == 0 {
        return Ok(vec![]);
    }

    let repo = git2::Repository::open(repo_root).context("failed to open repository")?;

    // Collect the commits we're about to undo so we can report them
    let mut to_undo: Vec<UndoneCommit> = Vec::new();
    let mut walk = repo.revwalk().context("failed to create revwalk")?;
    walk.push_head().context("no commits to undo")?;

    for (i, oid_result) in walk.enumerate() {
        if i >= count {
            break;
        }
        let oid = oid_result.context("revwalk error")?;
        let commit = repo.find_commit(oid).context("failed to find commit")?;
        let message = commit.message().unwrap_or("").to_string();

        if !force && !looks_like_fg_commit(&message) {
            return Err(anyhow!(
                "commit {} ({}) does not look like an fg auto-commit.\n\
                 Use --force to undo it anyway.",
                &oid.to_string()[..8],
                message.lines().next().unwrap_or("").trim()
            ));
        }

        let files = count_commit_files(&repo, &commit);
        let time = commit.time().seconds();
        let committed_at = DateTime::<Utc>::from_timestamp(time, 0).unwrap_or_default();

        to_undo.push(UndoneCommit {
            oid: oid.to_string(),
            message,
            files,
            committed_at,
        });
    }

    if to_undo.is_empty() {
        return Err(anyhow!("no commits found to undo"));
    }
    if to_undo.len() < count {
        return Err(anyhow!(
            "only {} commit(s) in history, cannot undo {}",
            to_undo.len(),
            count
        ));
    }

    // Soft reset HEAD~count — all changes return to the index
    let target_ref = format!("HEAD~{}", count);
    let target_obj = repo
        .revparse_single(&target_ref)
        .with_context(|| format!("failed to resolve {}", target_ref))?;

    repo.reset(&target_obj, git2::ResetType::Soft, None)
        .with_context(|| format!("failed to soft-reset to {}", target_ref))?;

    info!(count, "soft-reset HEAD — changes back in index");
    Ok(to_undo)
}

/// Heuristic: a commit was created by `fg` if it matches conventional commit
/// format or starts with `auto:`.
fn looks_like_fg_commit(message: &str) -> bool {
    let first = message.lines().next().unwrap_or("").trim();
    // conventional commit: type(scope): subject  OR  type: subject
    let conventional = first.contains(": ")
        && first.split(':').next().map(|t| {
            let t = t.trim().trim_end_matches(')');
            let base = t.split('(').next().unwrap_or(t);
            matches!(
                base,
                "feat" | "fix" | "refactor" | "chore" | "test" | "docs" | "build" | "ci" | "perf" | "style"
            )
        }).unwrap_or(false);
    let legacy = first.starts_with("auto:");
    conventional || legacy
}

fn count_commit_files(repo: &git2::Repository, commit: &git2::Commit<'_>) -> usize {
    let tree = match commit.tree() {
        Ok(t) => t,
        Err(_) => return 0,
    };
    let parent_tree = commit
        .parent(0)
        .ok()
        .and_then(|p| p.tree().ok());

    repo.diff_tree_to_tree(parent_tree.as_ref(), Some(&tree), None)
        .map(|d| d.deltas().count())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fg_commit_detection() {
        assert!(looks_like_fg_commit("feat(git): introduce PushQueue"));
        assert!(looks_like_fg_commit("fix: rework validate"));
        assert!(looks_like_fg_commit("chore: drop stale files"));
        assert!(looks_like_fg_commit("auto: changed config.rs"));
        assert!(!looks_like_fg_commit("WIP: hacking on stuff"));
        assert!(!looks_like_fg_commit("Merge branch 'main' into feature"));
    }
}
